# tf syntax basics

## importing tensorflow and checking versioning

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


## creating tensors
Tensors are n-dimensional arrays.

In [5]:
hello = tf.constant("hello ")
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
world = tf.constant(" world")
print(world)

Tensor("Const_4:0", shape=(), dtype=string)


## creating/running sessions

In [10]:
with tf.Session() as sess:
    result = sess.run(hello + world)
#b'abcd' means Py3 -> bytes literal
print(result)

b'hello  world'


### creating more tensors

In [12]:
a = tf.constant(10)
b = tf.constant(20)
with tf.Session() as sess:
    result = sess.run(a + b)
print(result)

30


## more operations

In [13]:
const = tf.constant(10)
fill_mat = tf.fill((4, 4), 10)
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [15]:
myzeros = tf.zeros(4, 4)
myones = tf.ones((4, 4))
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)
myrandu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [16]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

### interactive sessions (only really useful in notebook setting)
Interactive sessions will force the notebook to treat each cell as if it were running in a live session.

In [17]:
sess = tf.InteractiveSession()

In [20]:
for op in my_ops:
    print(sess.run(op))
    #note: op.eval() provides similar(might be same) functionality as sess.run(op)
    print(op.eval())

10
10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[0 0 0 0]
[0 0 0 0]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[-0.77178746 -0.19339757 -0.92271847  0.04563428]
 [-0.71581036  0.77209145 -0.91141152 -0.50839615]
 [-1.07157993 -1.15179741 -0.29566249  0.88324201]
 [ 0.05773016  1.86933804 -0.15182434 -0.84630656]]
[[ 0.9812187  -0.39946851  0.70504618  0.4850336 ]
 [-1.2993027   0.92371505 -1.63018763  1.65394533]
 [-0.08597247  0.30595422  0.49892399 -0.1992044 ]
 [ 0.2509332   1.46716869 -0.63537014  0.50263643]]
[[ 0.8185513   0.3965193   0.22594631  0.99599314]
 [ 0.81093919  0.6478802   0.47375679  0.58505034]
 [ 0.23156679  0.24041045  0.5235287   0.74030197]
 [ 0.32922697  0.84606338  0.29997396  0.68840432]]
[[ 0.57340324  0.54575241  0.4169594   0.51060474]
 [ 0.50759923  0.00364542  0.622

## matrix multiplication

In [21]:
a = tf.constant([
    [1, 2],
    [3, 4]
])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [26]:
b = tf.constant([
    [10],
    [100]
])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [27]:
result = tf.matmul(a, b)

In [28]:
sess.run(result)

array([[210],
       [430]])